# Generated by Django 3.2.4 on 2021-07-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
