# Generated by Django 3.2.4 on 2021-07-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_thumbnails_book_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='type',
        ),
    ]
