# Generated by Django 3.2.4 on 2021-07-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_category_book_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
